name: Code Quality

on:
  push:
    branches: ["main", "feature/*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use the latest stable Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: "npm"

      - name: Uninstall yarn
        run: npm uninstall yarn

      - name: Install yarn
        run: npm install yarn

      - name: Install Dependencies
        run: yarn

      - name: Run Lint
        run: yarn lint
